# This is a sample build configuration for Javascript.
# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:4.6.0

pipelines:
  branches:
    master:
      - step:
          script:
            - npm install -g less
            - npm install -g less-plugin-clean-css
            - lessc --clean-css="--compatibility=ie8 --advanced" less/color.less stylesheets/color.css
            - cd stylesheets/
            - ls
            - pwd